export const SIGNUP_FIELDS_TYPE = {
  EMAIL: "EMAIL",
  USERNAME: "USERNAME",
  PASSWORD: "PASSWORD",
  CONFIRM_PASSWORD: "CONFIRM_PASSWORD",
  EMPLOYEE: "EMPLOYEE",
  COMPANY: "COMPANY",
  ACCOUNTING_SOFTWARE: "ACCOUNTING_SOFTWARE",
  SIGNUP_CONFIRM_CHECKBOX: "SIGNUP_CONFIRM_CHECKBOX",
};

export const SIGNUP_FIELD_KEY = {
  EMAIL: "email",
  USERNAME: "username",
  PASSWORD: "password",
  CONFIRM_PASSWORD: "confirmPassword",
  EMPLOYEE: "employee",
  COMPANY: "company",
  ACCOUNTING_SOFTWARE: "accountingSoftware",
  SIGNUP_CONFIRM_CHECKBOX: "confirmation",
};
